version: "2"
checks: 
  argument-count: 
    enabled: true
  
  complex-logic: 
    enabled: true
  
  file-lines: 
    enabled: true
  
  identical-code: 
    enabled: true
  
  method-complexity: 
    enabled: true
  
  method-count: 
    enabled: true
  
  method-lines: 
    enabled: true
  
  nested-control-flow: 
    enabled: true
  
  return-statements: 
    enabled: true
  
  similar-code: 
    enabled: true
  

exclude_patterns: 
- config/
- db/
- dist/
- features/
- "**/node_modules/"
- script/
- "**/spec/"
- "**/test/"
- "**/tests/"
- Tests/
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"



plugins:
  editorconfig:
    enabled: true
    channel: beta
        config:
          editorconfig: .editorconfig

# exclude_patterns:
#   - node_modules/*
#   - coverage/*
#   - tests/fixture/*
#   - package-lock.json
